kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-root-ca.crt
  namespace: kube-system
  labels:
    application: external-dns
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
